# Generated by Django 5.2.1 on 2025-05-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FODDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('object_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('risk_level', models.CharField(choices=[('H', 'High Risk'), ('M', 'Medium Risk'), ('L', 'Low Risk')], max_length=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='detections/')),
                ('acknowledged', models.BooleanField(default=False)),
            ],
        ),
    ]
